import turtle 
def draw_letter(letter, font_size):
    name_turtle.write(letter, font=("cour", font_size, "normal"))
    name_turtle.forward(10)
    
t=turtle.Turtle()
s=turtle.Screen()
s.bgcolor("yellow")
t.pensize(5)
t.speed(7)
t.hideturtle()
t.pencolor("white")
t.penup()
t.goto(-100,30)
t.pendown()
t.color("darkred")
t.begin_fill()
t.fd(200)
t.rt(90)
t.fd(60)
t.rt(90)
t.fd(200)
t.rt(90)
t.fd(60)
t.end_fill()
t.goto(-60,30)
t.color("orange")
t.begin_fill()
t.fd(60)
t.rt(90)
t.fd(120)
t.rt(90)
t.fd(60)
t.rt(90)
t.fd(120)
t.end_fill()
t.goto(30,90)
t.color("magenta")
t.begin_fill()
t.fd(60)
t.rt(90)
t.fd(50)
t.rt(90)
t.fd(60)
t.rt(90)
t.fd(50)
t.end_fill()
t.goto(-11,150)
t.color("red")
t.begin_fill()
t.circle(10)
t.end_fill()
t.color("black")
t.penup()
t.goto(-200,-100)
def draw_name(name):
    for letter in name:
        draw_letter(letter, 36)
t.write("Happy Birthday!:)")

s.exitonclick()